version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  app:
    build: .
    ports:
      - "8004:8004"
    depends_on:
      - mongo

  keploy:
    image: keploy/keploy:latest
    depends_on:
      - app
    command: ["test", "--test-path", "/app/.keploy/test", "--app-host", "app", "--app-port", "3000"]
    volumes:
      - ./:/app
    ports:
      - "6789:6789"
